In [1]:
import numpy as np

In [8]:
seno = np.array[3]
seno

TypeError: 'builtin_function_or_method' object is not subscriptable

In [7]:
print(seno)

3


In [13]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
x = np.zeros(3)
y = np.array([1, 2, 3])
z = x + y 
z

array([1., 2., 3.])

In [15]:
x

array([0., 0., 0.])

In [16]:
y

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
y = np.ndarray(2)
y

array([1.04566038e-311, 6.95302063e-310])

In [19]:
y

array([[[1.04567921e-311, 3.16202013e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 6.64666107e-066]],

       [[8.30833310e-067, 7.48997028e-067, 1.93275547e-076],
        [9.59228065e-043, 4.23428739e+175, 3.11403373e+179]]])

In [28]:
y = np.ndarray([3])
print(y)
total = np.sum(y)
total

[1. 2. 3.]


6.0

In [31]:
np.cos(3.141592)


-0.9999999999997864

In [32]:
print(np.pi)

3.141592653589793


In [34]:
np.exp(1)

2.718281828459045

In [36]:
import math

math.exp(2)

7.38905609893065

In [42]:
math.exp(-0)

1.0